language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install tox-travis coveralls
script:
  - tox
sudo: false
git:
  depth: 250
env:
  global:
    - PYTHONHASHSEED=100
after_success:
  - coveralls